import type { Metadata } from "next";
import localFont from "next/font/local";
import { inter } from "@/app/ui/fonts";
import Header from "../ui/header/page";
// import "./globals.css";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: {
    default: "Create Next App",
    template: "%s | Products",
  },
  description: "Generated by create next app",
};

export default function LearningNextJSLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <br />
      {children}
      <br />
    </>
  );
}
